### PR TITLE
Add email for ordering attachment files in an alternative format

### PR DESCRIPTION
**Pull request by mgrassotti**
Add the email address for ordering attachment files in an alternative
format.

### CODE REVIEW

**Comment by fofr** [comment]
Looks good to me. Will we need to republish anything?

**Comment by mgrassotti** [comment]
@fofr we don't need republishing as it will be part of the Sync Checks

**Comment by fofr** [comment]
@mgrassotti Ok. Did you get the alternative email provider rendering locally in the end?

**Comment by mgrassotti** [comment]
@fofr unfortunately not because there is probably something going wrong with the republishing of the item locally. But, as the email is rendered by the presenter, the issue should be fixed now, so we could go on with this I think. 
The sync checks should highlight the problem if it appears again in integration.

**Pull request merged**
