### PR TITLE
Add pagination to document collections search via title results page .

### PR DESCRIPTION
**Pull request by farahTW**
This PR adds pagination functionality to search via title results page to add document.
It does the following:

- Added pagination logic for results page when searched via title.
- Updated controller tests
- Removed word slug from search via title views ,controller,controller_test-and routes files.

**Trello:**
https://trello.com/c/Idbzgryr/571-add-pagination-to-results-page-for-document-collections

**Screen shots:**

image

**When no results found:**
Screenshot 2023-10-09 at 15 32 19

### CODE REVIEW

**Comment by nnagewad** [comment]
From screenshots it looks good. Lets setup a session today to go over the spacing :)

**Comment by nnagewad** [comment]
What happens when there is only 1 to 15 search results returned?

**Comment by farahTW** [comment]
> What happens when there is only 1 to 15 search results returned?

It will not render pagination component as it is handled to show pagination when records > 15

**Comment by farahTW** [comment]
@nnagewad I have updated the message for no results found.Could you please check and let me know if it needs to be changed.
image

**Comment by nnagewad** [comment]
> @nnagewad I have updated the message for no results found.Could you please check and let me know if it needs to be changed. image

Just wondering why the content has changed?

**Comment by farahTW** [comment]
> > @nnagewad I have updated the message for no results found.Could you please check and let me know if it needs to be changed. image
> 
> @farahTW just wondering why the content has changed?

 @nnagewad As discussed reverted back the message.
image

**Review by minhngocd — APPROVED** [review]

**Comment by minhngocd** [comment]
LGTM

**Pull request merged**
