### PR TITLE
Make it clearer that statistics are official or national

### PR DESCRIPTION
**Pull request by benilovj**
The lack of labels on GOV.UK for official statistics are confusing users. 

Statistics publishers have been publishing non-statistics in the existing 'statistics' content-type (which is actually for official statistics).

This PR contains changes to work around the fact that `detailed_format`, a Rummager value derived from the publication type name is used in Rummager and for email alert URLs. These values shouldn't change for `OfficialStatistics` and `NationalStatistics` so that email alerts and document filtering doesn't break.

https://trello.com/c/TxBvx7tD/27-make-it-clearer-that-statistics-are-official-or-national-medium

### CODE REVIEW

**Comment by boffbowsh** [comment]
One small comment, otherwise it makes sense :+1:

**Comment by benilovj** [comment]
@boffbowsh simplified the code as per your suggestion (3abafd3)

**Comment by boffbowsh** [comment]
:sparkles: :star2: :star: :+1: :star: :star2: :sparkles:

**Comment by benilovj** [comment]
@jamiecobbett – just a heads up, I'm rebasing 1f63867cd020b8f43e8bd0d6c826253bfbce338e out of this PR because:

- this copy change is as yet not fully agreed with the content team and fact-checking organisations
- it's holding up the release of the re-labelling

**Pull request merged**
