### PR TITLE
Upgrade Ruby to 2.2.2

### PR DESCRIPTION
**Pull request by boffbowsh**
A few gem upgrades:
- kgio 2.8.0 wasn't compatible
- raindrops 0.11.0 wasn't compatible
- babosa had a duplicated key in a hash, which Ruby 2.2 has a warning for

In one of our tests, we were defining a key twice in the same hash, causing a warning. This has been fixed.

### CODE REVIEW

**Comment by bradleywright** [comment]
I think we can probably delete raindrops. Whitehall is the only app that uses it now, and I don't think we ever look at it.

**Comment by boffbowsh** [comment]
Looks like it's monitored by collectd atm? https://github.gds/gds/puppet/blob/85ee6899539495ac99f98aa23d66e52d665f1e81/modules/govuk/manifests/apps/whitehall.pp#L46

**Comment by alext** [comment]
I reckon that collectd raindrops plugin could be removed because we can get the same information from the [tcpcons plugin](https://github.gds/gds/puppet/blob/master/modules/govuk/manifests/app/config.pp#L195-L199).  The latter is probably more accurate because it gets the information from the kernel as opposed to making an HTTP request to the app.

**Comment by boffbowsh** [comment]
I'm fine with the above, but as it sounds like doing some Ops-y changes too, can we leave it for a different PR?

**Comment by alext** [comment]
> can we leave it for a different PR?

That sounds entirely reasonable to me.

**Comment by bradleywright** [comment]
:+1:

**Comment by bradleywright** [comment]
Just a reminder that this will need babysitting out (hard restart) as Ruby version changes don't restart cleanly under Unicorn.

**Comment by boffbowsh** [comment]
Thanks. Will merge after Edds' Whitehall deployment later, and rehearse in Preview.

**Comment by boffbowsh** [comment]
Putting this on hold until I have time to babysit it.

**Pull request closed without merging**
