### PR TITLE
Move Dashboard page to the GOV.UK Design System

### PR DESCRIPTION
**Pull request by davidgisbey**
## Description

 This adds the dashboard index view in the GOV.UK Design System.

 As the like for like implementation didn't really work with both the draft and force published editions taking up half the page
 each, i've largely copied the design in Carlos' prototype.

## Screenshot

image

## Trello card

https://trello.com/c/1gMHaPpS/19-dashboard-page

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

### CODE REVIEW

**Comment by cbernardojr-gds** [comment]
@davidgisbey 

Looks great!

Few comments and suggestions:
- Add some more space between the force-published title and the table above (govuk-!-margin-bottom-9 or govuk-!-margin-top-9)
- Question: Should it be View? Or should it be Edit for Drafts and Review for force-published?
- Recommendation: In the user research, we got feedback about the Guidance taking too much space. Here is a design suggestion with the guidance in the footer instead:
screencapture-gds-wh-herokuapp-v2-dashboard-2023-03-31-11_28_00
https://gds-wh.herokuapp.com/v2/dashboard/?prototypeVersion=v2
Password: wh1t3h@11

**Comment by davidgisbey** [comment]
I'm going to hold off on merging the design guidance into the footer because it would take substantial work and i think footers should probably be consistent across the application. We could change this in future but i think it needs more thinking/research and is out of scope for the transition work.

**Review by CL-GDS — APPROVED** [review]
LGTM

**Comment by nnagewad** [comment]
This looks great. Just wondering what happens if there are no documents under the "My draft document" heading

**Pull request merged**
