### PR TITLE
Modern slavery statement

### PR DESCRIPTION
**Pull request by MuriloDalRi**
https://trello.com/c/Yda37Ncb/2570-add-modern-slavery-statement-to-list-of-corporate-information-for-organisations-whitehall-publisher-3

### CODE REVIEW

**Review by brucebolt — CHANGES_REQUESTED** [review]
It looks like the changes to the locale files will need rebasing against `main`.

Also some of the translations appear to have been removed in the second commit (e.g. `speaking_notes --> other: Çıxış üçün  qeydləri` in Azerbaijani).

**Comment by MuriloDalRi** [comment]
> It looks like the changes to the locale files will need rebasing against `main`.
> 
> Also some of the translations appear to have been removed in the second commit (e.g. `speaking_notes --> other: Çıxış üçün qeydləri` in Azerbaijani).

So I'm running the task specified [here](https://github.com/alphagov/whitehall/blob/main/docs/internationalisation_guide.md#adding-a-new-translation-key) and that seems to mess up all the translations

**Comment by MuriloDalRi** [comment]
@brucebolt I've manually fixed all translations so it should be ready for review again

**Review by brucebolt — APPROVED** [review]
Thanks @MuriloDalRi.  Looks good to me.

**Pull request merged**
