### PR TITLE
Update historical buildings pages

### PR DESCRIPTION
**Pull request by injms**
## What

The following five pages:

 - https://gov.uk/government/history/10-downing-street
 - https://gov.uk/government/history/11-downing-street
 - https://gov.uk/government/history/king-charles-street
 - https://gov.uk/government/history/lancaster-house
 - https://gov.uk/government/history/1-horse-guards-road

don't have the updated link focus states. This pull request updates these pages with the new focus state, components where possible, and the layout has been updated to use the grid from GOV.UK Frontend.

## Why

The new focus state meets WCAG 2.1 accessibility requirements. Increasing the use of components and Frontend will lead to a lower amount of styles bespoke to this app in the future.

## Visual Changes

Title before:

image

Title after using component:

image

---

<table>
<tr>
<td>

Contents menu before:

image

</td>
<td>

Contents menu after:

image

</td></tr></table>

---

Headings before:

image

Headings after:

image

---

Blockquote before:

image

Blockquote after:

image

---

Inline link and image caption before:

image

Inline link and image caption after:
image

### CODE REVIEW

**Comment by andysellick** [comment]
Very small thing... the space between images and captions on https://www.integration.publishing.service.gov.uk/government/history/10-downing-street has decreased.

Before:

Screenshot 2020-02-20 at 09 57 32

After:

Screenshot 2020-02-20 at 09 56 44

**Comment by andysellick** [comment]
Quotes have lost their opening quote marks on mobile (although it wasn't great before, to be fair)

Before:

Screenshot 2020-02-20 at 09 59 07

After:

Screenshot 2020-02-20 at 09 59 12

**Comment by andysellick** [comment]
The heading structure on https://www.gov.uk/government/history/10-downing-street has been a bit flattened - all the H3s are now H2s, for example, this should be a H2 and a H3, but it's two H2s:

Screenshot 2020-02-20 at 10 02 46

**Comment by andysellick** [comment]
I don't know why, but the link above the page title when focussed is quite close to the heading. It must be to do with something conflicting with the component, but I can't spot it.

In the page:

Screenshot 2020-02-20 at 10 13 11

In the component guide:

Screenshot 2020-02-20 at 10 14 23

**Comment by andysellick** [comment]
Heading levels need checking on https://www.gov.uk/government/history/king-charles-street as well.

**Comment by injms** [comment]
> I don't know why, but the link above the page title when focussed is quite close to the heading. It must be to do with something conflicting with the component, but I can't spot it.
> 
> In the page:
> 
> Screenshot 2020-02-20 at 10 13 11
> 
> In the component guide:
> 
> Screenshot 2020-02-20 at 10 14 23

This is probably because the component on the publishing components site uses the new version of the font (`GDS New Transport`) with line-height improvements, and Whitehall is still using the old version of the font (`nta`)without these. This should be fixed when the `$govuk-compatibility-govuktemplate` flag is removed.

**Comment by injms** [comment]
cheers @andysellick - all those bits have been fixed. Give me a shout when you're available to take a look at it once more and I'll pop it onto integration again.

**Pull request merged**
