### PR TITLE
Remove all Import-related code

### PR DESCRIPTION
**Pull request by tekin**
The import feature was used during transition to mass-import documents from transitioning websites. Since transition is over, it is no longer required and can be removed.

To remove the importer, the behaviour of the speed tagger has had to be changed slightly. Previously, it was possible to speed-tag an imported edition and automatically be redirected to the next imported edition to be tagged. This was done by finding the next document from the Import the first document was
imported in. Because the Import code does not exist anymore, it isn't possible to find the next document. Instead, the user is redirected to the edition show page.

## Things to do after this has been merged and safely deployed

* Drop the related tables: `force_publication_attempts`, `import_errors`, `imports`
* Remove defunct import_id column from `document_sources` table
* Remove document-source editing functionality (this is probably redundant now that transition is complete)
* Remove the `IMPORT` user permission from whitehall and signon

### CODE REVIEW

**Comment by rjw1** [comment]
Shame this wouldnt get you to over 300,000 deleted lines

**Comment by elliotcm** [comment]
We held off deleting this in case there was further importing to be done for hold-out orgs.  Now Tekin has left, does anyone know if this is a realistic worry?  @bradleywright?

**Comment by tekin** [comment]
There was an email exchange with the transition content folk with GOV.UK product folk CC'd. Best to speak to Mark S. or Neil. W. The verdict was that the exiting import functionality was built specifically for transition, is flakey and not worth continuing to support and maintain on the off chance that it might be used again in the future. If a need to mass-import content in the future arises, a suitable solution can be found.

**Comment by jamiecobbett** [comment]
I am enthusiastic about merging this given how much code we'd get rid of. Do you have any thoughts, @marksheldonGDS?

**Comment by bradleywright** [comment]
@jamiecobbett it's fine to get rid of this code, but this PR no longer merges cleanly.

**Comment by jamiecobbett** [comment]
This gets rid of 3.62% of Whitehall's code, according to `rake stats` :100:

**Pull request merged**
