### PR TITLE
Revert hide political checkboxes and add guidance

### PR DESCRIPTION
**Pull request by edds**
Show the checkboxes for managing editors and show a link to the guidance on how to use the checkbox.

screen shot 2015-03-24 at 13 57 19

https://trello.com/c/fhJ4IXM0/150-make-history-mode-checkbox-available-for-managing-editors

### CODE REVIEW

**Comment by fofr** [comment]
This copy feels quite loose, and asks the user to make a few mental jumps:
* What is "government of the time" and then, "which government was that"?
* What is "label as associated"?
* What is "history mode"?

The copy is also not on style, there's no active voice.

Can the app do some of the work for the user? ie tell the user what the government of the time was
eg "[ ] Associate with _2010 to 2015 conservative and liberal democrat coalition government_"

**Comment by edds** [comment]
One of the problems is that the government association could change based on the first published date which they can edit below. So we can't say for sure that it will be associated to a given government without some JavaScript to dynamically update the label for that input. I have changed it to give you an indication as to which government it should be associated to. What do you think? Is that better?

screen shot 2015-03-26 at 12 23 00

**Comment by fofr** [comment]
Good point about the "first published" caveat. Changes look good. :+1:
All looks good except for test failures.

**Comment by edds** [comment]
Fixed the failing test which was caused by the test not creating a government that was around when the edition was created.

**Comment by dsingleton** [comment]
LGTM.

**Pull request merged**
