### PR TITLE
Remove tika jar file

### PR DESCRIPTION
**Pull request by boffbowsh**
This was added in bebb38846e576e9901bc12a7ed1d86e6e2fdca9e but the feature as a whole was removed in 7d3b17f9f71dcee632c40c2d600edaf08198e1f5

### CODE REVIEW

**Comment by fofr** [comment]
> (while leaving it in place for HTML attachments because they don't have the same external processing requirements - we just run the body through Govspeak)

Is that still the case?

**Comment by boffbowsh** [comment]
I can't find anything in Whitehall that uses this.

**Comment by boffbowsh** [comment]
Tika was only used for PDF extraction, not for Govspeak where we have the full text anyway

**Comment by fofr** [comment]
Trying to find the commit that removed the `- jar` line. Probably fine though.

**Comment by fofr** [comment]
Found it: https://github.com/alphagov/whitehall/commit/8eb622ed6c37a98809345b83b9cac615b2f4b9b0

**Comment by fofr** [comment]
:+1:

**Pull request merged**
