### PR TITLE
Switch Detailed Guide rendering app to government-frontend

### PR DESCRIPTION
**Pull request by tvararu**
This will display PDF attachment previews using draft-origin, which will allow us to test whether https://trello.com/c/1GUkYF5j/318-6-detailed-guides-migration-final-tasks-deploy-2-0-5-days is good to go.

### CODE REVIEW

**Comment by fofr** [comment]
What's the difference between the rendering app in the model and the rendering app in the presenter?

**Comment by tvararu** [comment]
@fofr it seems like the preview document URL is determined from the `rendering_app` on the model: https://github.com/alphagov/whitehall/blob/change-detailed-guide-rendering-app/app/helpers/public_document_routes_helper.rb#L49

**Comment by boffbowsh** [comment]
You're correct. Model rendering_app determines which url is given from whitehall admin. The one in presenter determines which frontend app is used for the content item.

**Comment by boffbowsh** [comment]
Test this on Integration first please. Looks 👍 though

**Comment by tvararu** [comment]
@boffbowsh thanks for the input, I figured out that I also had to do https://github.com/alphagov/whitehall/pull/2932/files#diff-805bcf4ab753fb66d137c6d2f891f53dR24. I think this is clear now.

**Comment by tvararu** [comment]
Can confirm this works on integration.

**Pull request merged**
