### PR TITLE
Switch to using govuk_admin_template and Bootstrap 3

### PR DESCRIPTION
**Pull request by fofr**
__Review using `?w=1` as many changes involved adding or removing HTML wrappers and altering indentation.__

This is a large but also _minimal_ pull request. I have aimed to keep it as small as possible – so that the majority looks and works exactly as it did before. The commits are predominantly class changes and the large bulk of it is:

* switching from Bootstrap 2 to Bootstrap 3 grids
* switching to Bootstrap 3 button classes
* updating modals to new syntax
* updating icon classes to use new glyphicons
* switching to Bootstrap 3 form classes, styles are no longer applied automatically (mostly `form-control` and `form-group`)
* updating `alert-` classes, mostly `alert-error` to `alert-danger`
* minor typography improvements along the way
* adding `list-unstyled` to remove Bootstrap 3’s default list styles where they aren't wanted

Some parts did require more attention and it's worth pointing those out:
* The force publish modal on a link needed a shim to work with Bootstrap 3
* The admin gem was updated so the Whitehall header could be used without significant changes
* The words to avoid highlighter picked up some styles from the admin gem because of a class clash
* Bootstrap 3 is more flexible in its use of horizontal form fields, but they now depend on grid classes, making a generic helper more complex. Horizontal form fields have been removed.
* Bootstrap 3 doesn't support IE6, IE6 specific styles have been removed (4 sessions  since January used IE6)
* Use a Chosen Bootstrap 3 theme

All changes should only affect the admin parts of Whitehall. It's probably worth leaving this on Preview for a short while once we're happy with it, to try and spot anything that's been missed.

https://www.pivotaltracker.com/story/show/96072212

__Depends on https://github.gds/gds/puppet/pull/2995__

# Before and after screenshots

## New document
Before
screen shot 2015-06-23 at 16 20 05

After
screen shot 2015-06-23 at 16 19 50

## Document list
Before
screen shot 2015-06-23 at 16 22 19

After
screen shot 2015-06-23 at 16 22 04

## Dashboard
Before
screen shot 2015-06-23 at 16 27 10

After
screen shot 2015-06-23 at 16 26 58

## Featured documents
Before
screen shot 2015-06-23 at 16 26 17

After
screen shot 2015-06-23 at 16 26 08

## Collections
Before
screen shot 2015-06-23 at 16 25 28

After
screen shot 2015-06-23 at 16 25 14

## Edit document
Before
screen shot 2015-06-23 at 16 24 51

After
screen shot 2015-06-23 at 16 24 39

## Document summary
Before
screen shot 2015-06-23 at 16 23 42

After
screen shot 2015-06-23 at 16 23 31

### CODE REVIEW

**Comment by boffbowsh** [comment]
All the Ruby/Railsish stuff looks good to me :+1:

**Comment by alicebartlett** [comment]
On the new document page, the govspeak helper box code examples no longer wrap. This page has a bunch of changes that I think are fine, this is the only one that we should probably fix as the helper is now quite difficult to use:

(before)
screen shot 2015-06-24 at 13 51 24

(after)
screen shot 2015-06-24 at 13 51 16

**Comment by fofr** [comment]
@alicebartlett I put back the missing `pre` styles (`white-space: pre-wrap`) so that lines would wrap correctly and be readable. This has introduced a new problem, where wrapping happens at a point that can cause confusion. In the example below it suggests that a line break is needed in link markup (I've seen this sort of thing cause problems in Whitehall training).

What are your thoughts?

Before
screen shot 2015-06-25 at 08 24 38

After
screen shot 2015-06-25 at 08 24 49

**Comment by alicebartlett** [comment]
@fofr I would defer to what the whitehall behaviour was before. In this case, the behaviour was to have the wrap, so the markdown looks like:
[a url]
(https://your-link-here.com)
 or maybe even 

[a url]
(https://your-link-
here.com)

which is what you have.

**Comment by fofr** [comment]
@alicebartlett Preview looks like:
screen shot 2015-06-25 at 09 39 40

**Comment by alicebartlett** [comment]
@fofr (depending on your viewport width: 
screen shot 2015-06-25 at 09 51 48

**Comment by alicebartlett** [comment]
OK, I'm done reviewing now. Happy for this to be merged.

**Comment by fofr** [comment]
Thanks @alicebartlett! :smile: 

We're going to deploy this branch to preview for a few days to see if anything else surfaces.

**Comment by alicebartlett** [comment]
(p.s) Well done for getting this done, it was epic!

**Comment by mdo** [comment]
:heart_eyes_cat:

**Pull request merged**
