### PR TITLE
Add {stat-headline} markdown and styles for HTML publications

### PR DESCRIPTION
**Pull request by fofr**
https://trello.com/c/z4YmHWDp/127-html-pubs-add-markdown-to-allow-users-to-add-large-font-and-graphs-medium

> Departments are about to create and publish their Single Departmental Plans. These will be published to GOV.UK as HTML publications. Departments need to be able to pull out important figures periodically throughout the HTML publication in large font.

* Add guidance for the `{stat-headline}` markdown when adding and editing HTML publications
* Style the markup generated by these headlines on HTML publications only
* Add styles so the in-form preview shows an approximation of the final content
* Switches all HTML pubs to have the same text colour as GOV.UK

```
{stat-headline}*13.8bn* years since the big bang{/stat-headline}
```

## Guidance
screen shot 2015-10-09 at 12 32 24

## How to use it and preview
screen shot 2015-10-09 at 12 32 34
screen shot 2015-10-09 at 12 32 42

## Final HTML publication
screen shot 2015-10-09 at 12 33 20

cc @alextea

### CODE REVIEW

**Comment by boffbowsh** [comment]
:+1: from a codings POV

**Comment by jamiecobbett** [comment]
:+1:

**Comment by dsingleton** [comment]
:+1: from me

**Comment by jamiecobbett** [comment]
I have two thumbs :+1: :+1:

**Pull request merged**
