### PR TITLE
Upgrade Ruby to 2.2.3

### PR DESCRIPTION
**Pull request by elliotcm**
The issue with Govspeak which prevented this upgrade
were fixed in version 3.5.1 according to this
comment: https://github.com/alphagov/govspeak/issues/57#issuecomment-158916181

### CODE REVIEW

**Comment by benlovell** [comment]
I'd be wary of this. See #2399 for reference.

**Comment by elliotcm** [comment]
Hi @benlovell, please see the PRs referenced above.

**Comment by elliotcm** [comment]
Ah, the issues are in whitehall itself.  I'll look into replacing those.

**Comment by boffbowsh** [comment]
:+1: but please test on staging for a little while before deploying.

**Comment by elliotcm** [comment]
@boffbowsh Were the errors largely on public pages?

**Comment by boffbowsh** [comment]
Yes, ones with things like `mailto://foo@example.com` in the Govspeak

**Comment by elliotcm** [comment]
@boffbowsh Good, staging should hopefully pick them up then.  I'll block out Friday and let it run over the weekend too.

**Comment by boffbowsh** [comment]
Some errbit errors with this: https://errbit.staging.publishing.service.gov.uk/apps/53020d6c0da11585f10000e7/problems/5694f67a65786307ce930100
https://errbit.staging.publishing.service.gov.uk/apps/53020d6c0da11585f10000e7/problems/5694f72265786307ce900300

This is mainly due to invalid URLs in govspeak in the formats:
- `mailto://foo@example.com`
- `[A link](https://www.example.com/url-with-a-space-at-the-end )`

**Comment by elliotcm** [comment]
After some effort we've been unable to replicate these exceptions, even to the point of redeploying to staging.

We'll deploy it to staging again this weekend.

**Comment by boffbowsh** [comment]
:+1:

**Comment by elliotcm** [comment]
After running it again Friday through Sunday we encountered no unexpected errors, so I'm merging this.

**Comment by benlovell** [comment]
:sparkles: :rocket:

**Pull request merged**
