### PR TITLE
Avoid duplicate corporate information pages

### PR DESCRIPTION
**Pull request by mgrassotti**
Add a new validation to avoid duplicate pages of the same type for a single organization.

### CODE REVIEW

**Comment by boffbowsh** [comment]
Looks good. Can you deploy it to integration and test some basic Corporate Information Page flows please?

**Comment by mgrassotti** [comment]
I did some test on 
[/organisations/animal-and-plant-health-agency/corporate_information_pages/623676](https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/organisations/animal-and-plant-health-agency/corporate_information_pages/623676):
- with the other page still present ([/623664](https://whitehall-admin.integration.publishing.service.gov.uk/government/admin/organisations/animal-and-plant-health-agency/corporate_information_pages/623664)): 
  - create a new edition **failed**
- after destroying the other page, all tests **worked**: 
  - create a new edition
  - saving of the edits
  - force publishing

**Comment by boffbowsh** [comment]
:+

**Comment by mgrassotti** [comment]
Great, I am ready to merge it. Just one question, we didn't already delete the duplicate about page from Whitehall in production, did we?

**Comment by boffbowsh** [comment]
I don't believe so, no.

**Comment by mgrassotti** [comment]
Ok I will create a PR for that then...

**Comment by boffbowsh** [comment]
👍

**Pull request merged**
