### PR TITLE
Remove sticky navs

### PR DESCRIPTION
**Pull request by alextea**
As per https://github.com/alphagov/specialist-frontend/pull/99

Once the nav is longer than the viewport height it’s impossible to see the bottom of it, unless you scroll right to the end of the page.

This PR removes the functionality, and a set of associated workarounds and styling.

### CODE REVIEW

**Comment by tijmenb** [comment]
:+1:

**Comment by fofr** [comment]
I think these tests also need removing:
https://github.com/alphagov/whitehall/blob/remove-sticky-nav/test/javascripts/unit/stick_at_top_when_scrolling_test.js

Happy to see this go :smile:

**Comment by alextea** [comment]
@fofr thanks for pointing that out, removed now

**Comment by tombye** [comment]
Great work :+1:

**Comment by edds** [comment]
While I am not a huge fan of sticky navigations this seems like a rather sledgehammer approach to just remove them all. The issue in  alphagov/specialist-frontend#99 was because the navigation was dynamically generated from the content on the page which was editable in the admin and could vary greatly in length. Some of the navigations you have removed sticky from here though aren't variable in length and are hard coded to only have 4 or 5 different items. There is never any chance that for those formats the navigation will suddenly get longer in length without a developer having to make a conscious decision and hopefully look how this changes the visual page.

It would also be good to look at this alongside the alternative approach we took with detailed guidance. On detailed guidance we were aware that the sidebar navigation was going to get really long and we wouldn't have any control over its length so we implemented a different way to let people who get lost at the bottom of a long document get back to the navigation in an easy way. You can [see this in action on this page about Oil and gas: fields and field development](https://www.gov.uk/guidance/oil-and-gas-fields-and-field-development).

**Comment by alextea** [comment]
Hi @edds, this was to fix a bug raised against this page: https://www.gov.uk/government/collections/apprenticeship-standards – there will be many other collections with the same problem as some agencies have been using collections in ways they weren't originally designed for.

I did ask whether they should just be removed from collections or from the whole of whitehall in Slack. Happy to roll back to just remove it from collections or to open a ticket to look at using a similar pattern to detailed guidance.

**Comment by alextea** [comment]
After an offline chat with @edds I'm going to merge this

**Pull request merged**
