### PR TITLE
Remove worldwide priority code.

### PR DESCRIPTION
**Pull request by elliotcm**
[Edited by @fofr]

~~These have been extracted into policy papers and are being retired as a format~~
This format is being deleted. The data must be removed first, see https://github.com/alphagov/whitehall/pull/2563

New ticket: https://trello.com/c/AtYGioxe/321-worldwide-priorities-deleting-the-format-medium
Old ticket: https://trello.com/c/JDieICof/117-remove-worldwide-priorities-code-from-whitehall

### CODE REVIEW

**Comment by fofr** [comment]
I've rebased this against master, up to date branch here:
https://github.com/alphagov/whitehall/tree/delete-everything-worldwide-priorities

Looking at this again as part of:
https://trello.com/c/USv09XGY/320-worldwide-priorities-prep-work-so-we-can-delete-the-format-medium
https://trello.com/c/AtYGioxe/321-worldwide-priorities-redirects-and-deleting-the-format-medium

**Comment by boffbowsh** [comment]
👍

**Comment by fofr** [comment]
The data has now been deleted.

**Comment by elliotcm** [comment]
🎉

**Pull request merged**
