### PR TITLE
Transition All users page to GOVUK design system.

### PR DESCRIPTION
**Pull request by farahTW**
This PR transits ALL users page to GOVUK design system.
It does the following:

- Duplicates existing index view and controller test to legacy.
- Added new index view with design system and updates the relevant files.

**Screen shots:**
**Before:**
image

**After:**

image

**Trello:**
https://trello.com/c/vHSW3bzf/549-transition-all-user-page-to-design-system

### CODE REVIEW

**Comment by nnagewad** [comment]
Looking good @farahTW , but what is up with the spacing. Why are they not presented on the same level

- Individual user name aligned in the middle of the row
- While role and organization is aligned to the top of the row

**Comment by farahTW** [comment]
@nnagewad corrected the design.
image

**Comment by nnagewad** [comment]
Right on @farahTW 👍🏽

**Comment by RodneyJohnsonGDS** [comment]
Slight typo in the filter component label of the user's index view. Can be found in this file: app/views/admin/users/index.html.erb

label: "Filter by user,role or organisation", you have to add a space between the comma and role. 

Otherwise, everything looks good to me!

**Comment by farahTW** [comment]
> Slight typo in the filter component label of the user's index view. Can be found in this file: app/views/admin/users/index.html.erb
> 
> label: "Filter by user,role or organisation", you have to add a space between the comma and role.
> 
> Otherwise, everything looks good to me!

Hey @RodneyJohnsonGDS  
Updated the space.
image

**Review by RodneyJohnsonGDS — APPROVED** [review]
LGTM!

**Pull request merged**
