### PR TITLE
Fix spelling of GDS

### PR DESCRIPTION
**Pull request by alexmuller**
This has been broken since e14caa3 in 2013.

### CODE REVIEW

**Comment by benlovell** [comment]
Whoops :see_no_evil:. Merge on :green_heart:

**Comment by alexmuller** [comment]
Pushed another few commits. The last one (ccd3c88d8b5d723cf712046a52f349cbe7287462) is incredibly disappointing and probably means we should have some conversations (@daibach).

**Comment by fofr** [comment]
@alexmuller www.bigsocietyawards.org is in the whitelist for Transition redirects. It should probably be removed from there too, and any redirects updated.

**Comment by alexmuller** [comment]
Good catch @fofr :+1:

**Comment by daibach** [comment]
Thanks @fofr. @jennyd Has looked at this and updated associated redirects.

**Comment by jennyd** [comment]
I've removed it from the whitelist as well, so mappings can't be set to redirect there again.

**Pull request merged**
