### PR TITLE
Cleaning up the codebase from unused methods

### PR DESCRIPTION
**Pull request by Davidslv**
Hello,

Just thought it would be nice to remove some unused methods, there's more but I tried to focus only on the helper methods that seem to not be used anywhere.

Thanks

Trello for cross reference: https://trello.com/c/C89RwZ19/348-cleaning-up-unused-methods-on-whitehall

### CODE REVIEW

**Comment by boffbowsh** [comment]
Staging and Integration. Staging only receives public traffic, no admin traffic. Some admins use integration occasionally to test things.

**Comment by tijmenb** [comment]
Talking about this offline. I'm a little worried because it's so easy for one of these methods to be called by `send("thing_you" + "thought_wasnt_called")`. We'd have to go through each method to verify that it really isn't called, preferably by location the commit where the last callsite was removed.

**Comment by Davidslv** [comment]
It also might be useful to share the code that identified those methods: https://gist.github.com/Davidslv/64c3e300fc9e6e2e95e38128d8445d9b

**Comment by tijmenb** [comment]
Putting this back in planning for now - see https://trello.com/c/C89RwZ19

**Pull request closed without merging**
