### PR TITLE
Upgrade admin frontend gems

### PR DESCRIPTION
**Pull request by rubenarakelyan**
This PR upgrades gems that are used in rendering admin pages. It also makes a minor consequential change to a `kaminari` test.

Trello: https://trello.com/c/eg61wStW/78-upgrade-whitehall-to-a-supported-version-of-rails

### CODE REVIEW

**Comment by rubenarakelyan** [comment]
Yes good idea - @fofr or @nickcolley?

**Comment by nickcolley** [comment]
We could split this into changes that only affect the admin side?

I agree with @gpeng we should be cautious

**Comment by rubenarakelyan** [comment]
I've updated the PR to only change the admin UI gems. It still updates `jquery-rails` as a dependency but not `jquery-ui-rails` any more.

**Comment by fofr** [comment]
Looks good to me. Can't see anywhere that the breaking changes in Kaminari or govuk_admin_template will cause problems.

**Comment by fofr** [comment]
Looks like this broke some analytics tracking in Whitehall, I'm guessing because of events that are being tracked without a category:
 
screen shot 2018-01-23 at 07 57 50

**Pull request merged**
