### PR TITLE
Remove WW priorities from publishing-api

### PR DESCRIPTION
**Pull request by mgrassotti**
Trello: https://trello.com/c/AtYGioxe/321-worldwide-priorities-deleting-the-format-medium

Publish redirects to Publishing Api, in order to remove legacy worldwide priorities contents, as defined here: https://docs.google.com/spreadsheets/d/1N3tvPceqG_7ASE9cET_lbQRdJevW_9h-UDtov_-uRlM/edit#gid=0

### CODE REVIEW

**Comment by boffbowsh** [comment]
👍

**Comment by fofr** [comment]
Nice :smile:

**Comment by binaryberry** [comment]
@mgrassotti Hi Matteo, the list you used is not the complete one - that was only the worldwide priorities that we needed to get feedback from departments for as they were associated with no or multiple countries. The full list is here: https://github.gds/gds/router-data/blob/master/data/worldwide_priority_redirects.csv

**Comment by mgrassotti** [comment]
👍 @binaryberry I'll create another pull request

**Comment by mgrassotti** [comment]
https://github.com/alphagov/whitehall/pull/2583

**Pull request merged**
