### PR TITLE
Update whitehall to Rails 4.1

### PR DESCRIPTION
**Pull request by tekin**
Now that whitehall is running on Rails 4.0, we should update to 4.1 ASAP as 4.0 is now end-of-life[1].

These are mostly minor adjustments to get around deprecation warnings and subtle changes in Rails API. The last commit is potentially more interesting - it adjusts some tests to get around a bug in Rails. In theory, the bug is still present, but it shouldn't manifest itself in the running application (we never directly assign organisations to topics in this manner). There is an open pull request[2] to fix the bug, so it should be fixed in a future Rails release.

I've worked up an alternative solution that overrides the setter (see the last commit of https://github.com/alphagov/whitehall/compare/rails41-setter-override). Given that there is an open pull request on Rails to fix the bug and that the buggy setter doesn't get used outside of the test suite, I think simply not using the setter is the best course of action for now; either we work around the bug if and when it becomes an issue in the app itself, or a future version of Rails will contain the fix, whichever comes first.

[1] http://weblog.rubyonrails.org/2015/1/6/Rails-4-1-9-and-4-0-13-have-been-released/
[2] https://github.com/rails/rails/pull/18198

### CODE REVIEW

**Comment by jamiecobbett** [comment]
Very clear and well-documented upgrade, thanks :+1: LGTM, but I'll leave it to people who know Whitehall better to review.

**Comment by benilovj** [comment]
this needs a rebase

**Comment by tekin** [comment]
Rebased

**Comment by tekin** [comment]
Current plan is to deploy this to preview and staging on Thursday so we can leave it running for a day or two to catch any unforeseen issues before merging and deploying to master Monday.

**Comment by heathd** [comment]
all looks good to me

**Pull request merged**
