### PR TITLE
Update Prime Minister

### PR DESCRIPTION
**Pull request by alexmuller**
Theresa May is the Prime Minister.

### CODE REVIEW

**Comment by whpearson** [comment]
Line 26 also needs updating He->She/They

**Comment by fofr** [comment]
Is the picture changing too?

**Comment by alexmuller** [comment]
Yep, we're just getting one through now

**Comment by jennyd** [comment]
We're deploying this branch (at 3cd5c8052bcb08806d8b67fc018c2d434bdbe482) to Production as a hotfix.

**Comment by dsingleton** [comment]
👏

**Comment by jabley** [comment]
Needs tests.

**Pull request merged**
