### PR TITLE
Upgrade mocha to v1.16.0 & fix deprecation warning

### PR DESCRIPTION
**Pull request by floehopper**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Comment by floehopper** [comment]
@chao-xian I created a new v1.x release of Mocha to add a deprecation warning for a method that will be removed in Mocha v2. This upgrades whitehall to Mocha v1.16.0 and fixes the deprecation warning relating to `Mocha::Configuration#reinstate_undocumented_behaviour_from_v1_9`. I'm still testing Mocha v2 and will get back to you once I'm happy with it.

**Comment by floehopper** [comment]
@chao-xian Can you kick off the CI workflow for this PR when you've got a minute? Thanks.

**Comment by chao-xian** [comment]
:+1: for your reference https://github.com/alphagov/whitehall/pull/6928 (I'm finishing for the day)

**Comment by chao-xian** [comment]
🤦 I thought this was your fork... this day needs to end.

**Comment by floehopper** [comment]
@chao-xian Thanks for kicking off the build. It looks as if the "CI / Test Rails / Test" workflow has passed. Unfortunately I can't see the failures in the "continuous-integration/jenkins/branch" workflow. I'd be surprised if they were anything to do with the Mocha upgrade, but let me know if I can help.

**Comment by floehopper** [comment]
Also I see you've now got a dependabot PR for this version bump (#6929), although it doesn't include [the commit which fixes the Mocha deprecation warning](https://github.com/alphagov/whitehall/pull/6927/commits/5121f0c5b985a6e6c1e38561cd0d839356545125).

**Comment by chao-xian** [comment]
```
Failures:
1) GOVUK.FilterOptions renders the request response to #search_results
  Message:
[31m    TypeError: Cannot read property 'withMock' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/views/editions/filter_options.spec.js:57:18)
        at <Jasmine>

2) jQuery.enablePreview should post to generate a preview when the preview button is clicked
  Message:
[31m    TypeError: Cannot read property 'install' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:29:18)
        at <Jasmine>
  Message:
[31m    TypeError: Cannot read property 'uninstall' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:35:18)
        at <Jasmine>

3) jQuery.enablePreview should show a loading state while the request is loading
  Message:
[31m    TypeError: Cannot read property 'install' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:29:18)
        at <Jasmine>
  Message:
[31m    TypeError: Cannot read property 'uninstall' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:35:18)
        at <Jasmine>

4) jQuery.enablePreview should hide the textarea when the request is complete and populate a preview
  Message:
[31m    TypeError: Cannot read property 'install' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:29:18)
        at <Jasmine>
  Message:
[31m    TypeError: Cannot read property 'uninstall' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:35:18)
        at <Jasmine>

5) jQuery.enablePreview should alert if the server responds with an error
  Message:
[31m    TypeError: Cannot read property 'install' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:29:18)
        at <Jasmine>
  Message:
[31m    TypeError: Cannot read property 'uninstall' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:35:18)
        at <Jasmine>

6) jQuery.enablePreview should empty the preview and show the editor again when clicking edit after previewing
  Message:
[31m    TypeError: Cannot read property 'install' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:29:18)
        at <Jasmine>
  Message:
[31m    TypeError: Cannot read property 'uninstall' of undefined[0m
  Stack:
        at UserContext.<anonymous> (http://localhost:38415/__spec__/admin_legacy/preview.spec.js:35:18)
        at <Jasmine>

148 specs, 6 failures
```

**Comment by floehopper** [comment]
Thanks. But those are all JavaScript tests, aren't they? Are they possibly flakey tests or do you think the failures were genuinely broken by the Mocha version bump. It's worth noting that the change in functionality between Mocha v1.15.0 -> v1.16.0 was minimal.

**Review by ollietreend — APPROVED** [review]
@floehopper @chao-xian I've just re-run the build in Jenkins and it passed – so must have been an unrelated failure.

Thank you for opening this PR ⭐ it looks good to me, so I'll go ahead and merge it in.

**Comment by chao-xian** [comment]
Sorry @floehopper I was about to rush to a series of meetings and copy pasted the output without parsing it

**Comment by floehopper** [comment]
Thanks, @ollietreend!

No worries, @chao-xian - thanks for all your help!

**Pull request merged**
