### PR TITLE
Extract entities from abbreviations

### PR DESCRIPTION
**Pull request by jackscotti**
As part of our 'GOV.UK Search and Navigation improvement' [Firebreak project](/https://gov-uk.atlassian.net/wiki/pages/viewpage.action?pageId=20185307) we need to extract 'abbreviations' from Editions.

Together with @heathd I created an extractor and a script that runs it through all the editions present in Whitehall. The script also outputs all the pairs in newline separated json.

ie:

{"terms":["Government digital service","GDS"],"type":"abbreviation"}
{"terms":["Ministry of Justice","MoJ"],"type":"abbreviation"}

### CODE REVIEW

**Comment by heathd** [comment]
I'll just add that Jack and I looked at adding a cucumber acceptance test for the script but it ran very slowly due to the overhead of booting up rails when invoking the external script, and I felt that given the current experimental nature of this code the extra complexity and overhead of the test execution time wasn't worth it, so we ditched it.

We could refactor the script to put the edition iteration/serialisation logic into a unit-testable module, but again I don't think that's a good value-for-effort trade-off right now as this code is currently experimental.

**Comment by edds** [comment]
There is some mixed whitespace in these commits. Would it be possible to rebase them and replace the soft tabs with two space tab indents please.

**Comment by rboulton** [comment]
Other than @edds' comment, I think this is fine to merge.

**Comment by jackscotti** [comment]
Done.

**Comment by edds** [comment]
Looks good to me. Feel free to merge when you have product sign off.

**Comment by heathd** [comment]
Thanks @rboulton @edds for the feedback.

Given that this is a developer-facing feature, then I think no further product review is needed (@rboulton and I will be using this, it's a command line script). 

So, @jackscotti you can go ahead and merge when ready.

**Pull request merged**
