### PR TITLE
Remove frontend detailed guide code from Whitehall

### PR DESCRIPTION
**Pull request by tvararu**
Depends on https://github.com/alphagov/whitehall/pull/2637.

Removes left-over logic and tests relating to displaying detailed guides.

### CODE REVIEW

**Comment by tvararu** [comment]
Rebased, very minute conflicts actually.

That was easy

**Comment by gpeng** [comment]
Don't forget cucumber 🍆 😉

**Comment by boffbowsh** [comment]
Do not merge. This is needed to preview attachments until we can make them work in the draft stack

**Comment by fofr** [comment]
@boffbowsh Given that https://trello.com/c/7lXuBrwM/497-pdfs-not-being-served-correctly-in-draft-government-frontend is done, can this be merged now?

**Comment by boffbowsh** [comment]
It'll need a proper re-testing. Has previewing been moved back to the draft stack yet?

**Comment by tvararu** [comment]
I had to remove one more mention from a test, see latest commit: 936b084.

**Pull request merged**
