### PR TITLE
Serve content images from CDN

### PR DESCRIPTION
**Pull request by boffbowsh**
https://trello.com/c/Dq2gQ1Nu/274-bug-with-images-in-government-frontend-on-case-studies-and-take-part-medium

Uses the `GOVUK_ASSET_HOST` environment variable instead of
`GOVUK_ASSET_ROOT` for the image host. This is needed because
`whitehall-backend` boxes are in charge of rendering the content, but
are configured to serve assets from `whitehall-admin.${app_domain}`.
That configuration was only intended for assets like CSS and JS.

This was previously opened as #2454. I've tested that this doesn't break image serving for admin preview in integration.

### CODE REVIEW

**Comment by benlovell** [comment]
Nice :ship:

**Comment by jamiecobbett** [comment]
I think the commit message on the second commit could be a bit more descriptive. It doesn't seem to actually describe the problem, just the causes. Additionally, whitehall-backend boxes render the Govspeak for migrated formats, not everything.

Separately, does it make sense to fold in the last commit to the second? Or perhaps an explanation of why those need to change.

**Comment by boffbowsh** [comment]
Good points @jamiecobbett, reworded.

**Comment by benilovj** [comment]
:+1:

**Comment by jamiecobbett** [comment]
:+1:

**Comment by benlovell** [comment]
:ship:

**Pull request merged**
