### PR TITLE
Unpublish withdrawn content items with state disparity

### PR DESCRIPTION
**Pull request by cbaines**
Trello ticket: https://trello.com/c/aoTVNMQz/741-withdrawn-content-items-should-be-labelled-as-such-in-the-publishing-api-medium

This branch contains a data migration to unpublish several editions from Whitehall that are in the "withdrawn" state, but in the "draft" or "published" state in the Publishing API.

It also bumps the dependency on gds-api-adapters as this is needed to unpublish drafts.

### CODE REVIEW

**Comment by cbaines** [comment]
@steventux kindly looked at this, and discussed the missing unpublishings with me, with the concern that the explanation will appear on the frontend, so the name of the migration file might not be appropriate.

In my local database, there is only one item with a missing unpublishing `5fee02a4-7631-11e4-a3cb-005056011aef`. Looking at the corresponding document on the frontend crashes the frontend [1].

1: https://www.gov.uk/government/publications/badgers-report-action-taken-under-licences-a01-and-a26

**Comment by cbaines** [comment]
Thanks to Liz, the document mentioned above with the missing unpublishing has now been fixed, so I have removed the code to cope with this.

I have also rebased this branch, and fixed the conflicts.

@steventux, could you take another look?

**Comment by steventux** [comment]
This looks ok, I'd be tempted to read the content id data from file(s) as the migration is obscured by this.

**Comment by boffbowsh** [comment]
👍 . I had similar misgivings about the content ids being in this file, but at least it's encapsulated and you don't have logic to read in a file within a migration.

**Pull request merged**
