### PR TITLE
redirect URLs with group ID

### PR DESCRIPTION
**Pull request by mgrassotti**

### CODE REVIEW

**Comment by boffbowsh** [comment]
Can you add a test for this, and also add a more descriptive commit message please?

**Comment by boffbowsh** [comment]
👍

**Comment by fofr** [comment]
I've noticed that the fix for this problem is currently contained within code that's due for deletion here:
https://github.com/alphagov/whitehall/pull/2526

**Comment by boffbowsh** [comment]
Yep, that PR will no longer merge cleanly. That PR will need to leave this change behind.

**Comment by fofr** [comment]
@boffbowsh But then the policies won't be redirected properly and those URLs will error on live.

**Comment by boffbowsh** [comment]
Why? If this redirect is still in place, requests for an integer id will still get redirected to the correct URL, which will be served by government-frontend.

**Pull request merged**
