### PR TITLE
Add data migration to retitle policies.

### PR DESCRIPTION
**Pull request by elliotcm**
This provides policy titles which are separate from
their implementation.

No slug changes at this stage.

https://trello.com/c/dgqOFUSB/97-retitle-policies

- [x] Code signoff
- [x] Product signoff
- [x] Final CSV

### CODE REVIEW

**Comment by elliotcm** [comment]
Local machine product signoff by @bmwelby

**Comment by dsingleton** [comment]
Fixed a typo for @bmwelby in 5802ef0.

**Comment by dsingleton** [comment]
Is this worth doing in a transaction, so we can rollback to a clean state if there are any problems?

**Comment by dsingleton** [comment]
The rest LGTM to me, but i'd suggest getting an OK from someone a little more familiar with `Edition`s too.

**Comment by bradleywright** [comment]
@dsingleton data migrations [run in a transaction](https://github.com/alphagov/whitehall/blob/master/lib/whitehall/data_migration.rb#L27-L41)

**Comment by dsingleton** [comment]
:+1:

**Comment by tekin** [comment]
Ran this locally and it completed fine :+1: 

One query I have: because `update_attribute` is being called, the `updated_at` timestamp is being set. This will result in all the policies being pushed to the top of the editions filter in admin:

screen shot 2015-03-26 at 18 05 21

This is almost certainly what we want, but just want to double check. /cc @bmwelby.

**Comment by elliotcm** [comment]
@tekin Good point, but that's been the case for every mass update we've done in the past.

**Pull request merged**
