### PR TITLE
Add Worldwide Organisation About Page

### PR DESCRIPTION
**Pull request by davidgisbey**
## Description

We're moving the about us information to it's own tab for worldwide organisations. This adds the tab to the helper method responsible for rendering the worldwide organisation tabs and then adds a new endpoint.

image

## Trello card

https://trello.com/c/HW4NnOjF/348-update-organisations-details-page-and-add-an-about-page

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

### CODE REVIEW

**Comment by nnagewad** [comment]
DOPE!

**Comment by davidtrussler** [comment]
@nnagewad It's a bit picky perhaps but the text in the "Body" section here has a slightly annoying top margin that pushes the text below the work "Body" in a way that doesn't happen in the "Summary" section. I think it would need a general solution to the component itself rather than being specific to this piece of work. @davidgisbey

**Comment by davidgisbey** [comment]
ah right i see what's happening. the `simple_format` method creates a para for it which adds margin to the top by default. I think we can override it by passing in `simple_format(truncate(@organisation.body, length: 500), class: "govuk-!-margin-top-0")`

Great spot will push up the fix.

**Review by davidtrussler — APPROVED** [review]
LGTM! 👍

**Pull request merged**
