### PR TITLE
Prevent creating or modifying policies & supporting pages.

### PR DESCRIPTION
**Pull request by elliotcm**
There is an entry in the election team tech debt
page to fully remove all of the remaining code,
this is just to prevent further modifications now
that policies are handled by the Policy Publisher.

https://trello.com/c/lCV3MbSO/201-disable-creating-and-editing-of-policies-in-whitehall

### New document menu
screenshot 2015-04-21 15 12 29

### Policies
screenshot 2015-04-24 14 10 30

### Supporting pages
screenshot 2015-04-24 14 10 58

### CODE REVIEW

**Comment by edds** [comment]
:+1: This looks good to me.

**Comment by elliotcm** [comment]
Followup from product; we need to refer users to GDS rather than policy publisher, and GDS admins should still be able to work as before to handle those requests.

**Comment by elliotcm** [comment]
@edds Code updated, needs re-review.
@bmwelby Screenshots updated, need re-review.

**Comment by elliotcm** [comment]
Product signoff from @bmwelby

**Comment by edds** [comment]
:+1:

**Pull request merged**
