### PR TITLE
Bump Ruby to 3.2.4

### PR DESCRIPTION
**Pull request by dj-maisy**
## What?
This bumps Ruby to 3.2.4.

## Related

* https://github.com/alphagov/govuk-ruby-images/pull/92

### CODE REVIEW

**Comment by sengi** [comment]
We might be able to drop the patch version entirely and just use the `3.2` tag. (Or does whitehall still have some issue that stops us from doing that?)

**Review by sengi — COMMENTED** [review]
Oh we should update /.ruby-version to match as well.

**Review by ryanb-gds — APPROVED** [review]

**Comment by kevindew** [comment]
Just to flag - as per a Slack chat - that .ruby-version needs a full version for rbenv which is the tool used in development environments.

If we want to go down this road we'd need to update govuk-docker and change guidance on dev environments to use a different ruby version manager.

**Comment by sengi** [comment]
Oh I think this was just a mistake — thanks for spotting!

**Pull request merged**
