### PR TITLE
Use ellipses instead of ...

### PR DESCRIPTION
**Pull request by jackscotti**
Resetting back what this PR:
https://github.com/alphagov/whitehall/pull/2249
inadvertently overrode from:
https://github.com/alphagov/whitehall/commit/d43ca793b97908884a77917022da35913dfdec8d

### CODE REVIEW

**Comment by fofr** [comment]
It looks like #2249 also altered some of the smart quote changes, from ' to ’

**Comment by rboulton** [comment]
These fixes look good to me.  Either make a separate PR for the smart-quote change, or add to this PR.  @fofr I could only spot one smart quote change that #2249 overrode - are there more than 1?

**Comment by jackscotti** [comment]
https://github.com/alphagov/whitehall/pull/2259

**Comment by jackscotti** [comment]
Got the good to go, therefore merging.

**Pull request merged**
