### PR TITLE
Remove consultation templates redux

### PR DESCRIPTION
**Pull request by andrewgarner**
Resurrection of #3006. We now have draft links so we can view draft [Consultations](https://docs.publishing.service.gov.uk/content-schemas/consultation.html) in [Government Frontend](https://docs.publishing.service.gov.uk/apps/government-frontend.html) and remove the presentation code from [Whitehall](https://docs.publishing.service.gov.uk/apps/whitehall.html).

See also #3067 and [Trello](https://trello.com/c/LYFL1ZH9/)

### CODE REVIEW

**Comment by fofr** [comment]
Have you tested locally by creating and previewing a consultation with links? Is it worth putting this on integration to double check?

Otherwise looks good to me, will leave @gpeng to approve.

**Comment by andrewgarner** [comment]
I've not tested locally no, but I'll deploy the branch to integration and do some manual testing.

**Comment by andrewgarner** [comment]
Tested successfully on integration by creating a consultation with both a new PDF and a HTML attachment and previewing the draft.

**Comment by nickcolley** [comment]
Epic work @andrewgarner thanks 👍

**Pull request merged**
