### PR TITLE
Link to the publication's whitehall-admin URL from the CSV export

### PR DESCRIPTION
**Pull request by issyl0**
- The default not being `whitehall-admin.ENV.alphagov.co.uk` was
  confusing to people using the CSV export feature as they then had to
  copy and paste the path onto the end of a whitehall-admin URL. This
  makes `whitehall-admin.ENV.alphagov.co.uk` the default (using the
  existing `Whitehall.admin_host` method) and gives the ability to
  specify a hostname (e.g. `www.gov.uk`) in the parameters for
  `admin_edition_url`.

Thanks to @evilstreak for helping with this!

### CODE REVIEW

**Comment by issyl0** [comment]
This means that we can get rid of `host: Whitehall.admin_host` parameters in all calls to `admin_edition_url`, as it's now the default. Should I do that now?

A search reveals their existence in https://github.com/alphagov/whitehall/blob/master/test/unit/helpers/govspeak_helper_test.rb#L42, https://github.com/alphagov/whitehall/blob/master/lib/tasks/export.rake#L80, https://github.com/alphagov/whitehall/blob/master/lib/tasks/export.rake#L121, https://github.com/alphagov/whitehall/blob/master/lib/whitehall/exporters/redirector_document_mappings.rb#L24, and all through https://github.com/alphagov/whitehall/blob/master/lib/whitehall/exporters/redirector_document_mappings.rb.

**Comment by evilstreak** [comment]
That sounds like a good idea to me

**Comment by issyl0** [comment]
@evilstreak Done.

**Comment by wryobservations** [comment]
:+1:

**Comment by boffbowsh** [comment]
LGTM :+1:

**Comment by issyl0** [comment]
Thanks!

**Pull request merged**
