### PR TITLE
Convert worldwide priorities to policy papers.

### PR DESCRIPTION
**Pull request by elliotcm**
- [ ] FCO signoff

These are being retired.

Initial product review completed locally, will re-review with a branch on preview.

https://trello.com/c/QNQHpiym/177-convert-worldwide-priorities-into-translated-html-attachments-on-policy-papers

### CODE REVIEW

**Comment by edds** [comment]
:+1:

**Comment by edds** [comment]
New changes look :+1:

**Comment by elliotcm** [comment]
When deploying this a CSV will be output on the machine it runs on.  Please add that CSV to [this trello ticket](https://trello.com/c/uWJzuUYr/327-publish-worldwide-priority-pages) as it will be needed to know which editions to publish.

**Comment by jennyd** [comment]
We're not able to finish this piece of work at the moment due to complications with converting translated worldwide priorities to PDFs, so I'm closing the 3 related PRs for now - we can reopen them when we pick this up again.

**Pull request closed without merging**
