### PR TITLE
Remove org logos from people

### PR DESCRIPTION
**Pull request by alicebartlett**
https://www.pivotaltracker.com/n/projects/1261204

This PR removes org logos from the people pages. The design is different to that in the pivotal ticket in order to accommodate the case where the role is associated with more than one organisation (see http://gov.uk/government/people/david-cameron)

Screen shots:
(with a "more" link: http://gov.uk/government/people/lord-nash)
screen shot 2015-06-16 at 11 38 43

(no more link present: http://gov.uk/government/people/tracey-newman)
screen shot 2015-06-16 at 11 38 37

(more link and multiple orgs: http://gov.uk/government/people/david-cameron)
screen shot 2015-06-16 at 11 38 27

The first commit is the fix, and subsequent commits are refactoring out some code that is made redundant by the removal of the logos from the people page.

It's possible that there is more code that has been made obsolete by the deletion of `_organisations_logo_list.html.erb`, but they're a bit difficult to track down and I'm not especially familiar with the organisation logo work. If you can find more things that could be deleted as part of this pull request, leave a comment. I'll pay 1 celebration (sweet) per line you find.

### CODE REVIEW

**Comment by boffbowsh** [comment]
I will sacrifice some chocolate for the sake of readability: :+1:

**Comment by edds** [comment]
I think you can also delete this line now: https://github.com/alphagov/whitehall/blob/8941f7abe2c1c7247c407204c06bed1668216f62/app/assets/javascripts/application/on_ready.js#L14

**Comment by edds** [comment]
I think you can also delete https://github.com/alphagov/whitehall/blob/8941f7abe2c1c7247c407204c06bed1668216f62/app/assets/stylesheets/frontend/views/_biographical-page.scss#L58-L68 and https://github.com/alphagov/whitehall/blob/8941f7abe2c1c7247c407204c06bed1668216f62/app/assets/stylesheets/frontend/views/_biographical-page.scss#L19-L21

**Comment by edds** [comment]
I *think* you might be able to get rid of this now also: https://github.com/alphagov/whitehall/blob/8941f7abe2c1c7247c407204c06bed1668216f62/app/assets/stylesheets/frontend/helpers/_page-header.scss#L36-L42 as the HM Government was only inserted from that partial.

**Comment by edds** [comment]
This is also the last use of `organisation.headings.plus_others` so all these lines can go: https://github.com/alphagov/whitehall/search?q=plus_others

**Comment by edds** [comment]
I also think the `organisation.type.*` translation keys don't get used any more as they were only being used in the `_organisations_logo_list.html.erb` file. Which means these tests: https://github.com/alphagov/whitehall/blob/master/test/unit/i18n_key_test.rb#L55-L62 and these for every translation option: https://github.com/alphagov/whitehall/blob/master/config/locales/en.yml#L351-L395

**Comment by edds** [comment]
Assuming the tests pass this LGTM :+1:

**Pull request merged**
