### PR TITLE
[DO NOT MERGE] Rename `Topic` to `Policy Area`

### PR DESCRIPTION
**Pull request by jackscotti**
We are renaming the bits which say "topic" in the whitehall-admin to say "policy area".

This work needs to go in advance of renaming "specialist sector" to "topic" in whitehall-admin.

Needs coordination with comms and content team for deployment; also needs coordination with this zendesk ticket: https://govuk.zendesk.com/agent/tickets/1021549

### CODE REVIEW

**Comment by alext** [comment]
This needs some detail in the commit message (and the PR description).  Most importantly, it should explain why this change is being made.

See https://github.com/alphagov/styleguides/blob/master/git.md for more detail.

**Comment by jackscotti** [comment]
I pushed this up only for having Jenkins to run the tests. I will update code/commit/description shortly.

**Comment by alext** [comment]
Ah, that makes sense now...

For future, it's not necessary to open a pull-request if you just want the tests to be run, Jenkins is triggered every time a branch is pushed.

**Comment by jackscotti** [comment]
Didn't know that, thanks! Will do from next time.

**Pull request closed without merging**
