### PR TITLE
Change text colour to sass variable

### PR DESCRIPTION
**Pull request by edwardhorsford**
This PR changes the colour used by the pluses graphic to our SASS variable for secondary text colour.

This improves the contrast from  2.85:1 to 4.56:1.

### CODE REVIEW

**Comment by jamiecobbett** [comment]
If people are reluctant to merge this, would a screenshot help? It would help me to understand what the change is.

**Comment by edwardhorsford** [comment]
I'm not set up to run whitehall, so I've edited in browser to preview what it *should* look like. Note this requires that sass compilation is working and that the standard GOV.UK colour pallete is available.

Before:
screen shot 2016-01-28 at 14 38 35


After:
screen shot 2016-01-28 at 14 39 07

**Comment by bradwright** [comment]
Seems fine :+1:

**Comment by jamiecobbett** [comment]
@edwardhorsford the convention with this repo is to merge once someone else has given :+1:, so if you're happy to merge, please go ahead.

**Comment by edwardhorsford** [comment]
Good to know, thanks @jamiecobbett

**Pull request merged**
