### PR TITLE
Remove performance test, fixes `rake default`

### PR DESCRIPTION
**Pull request by boffbowsh**
Story: https://www.pivotaltracker.com/story/show/96896112

`rake default` runs all tests, including features and benchmarks. The single benchmark test we have requires `benchmark_helper`, which due to the ordering of `require`s ends up loading `config/environment` whilst in the `benchmark` Rails env. This means that gems such as `factory_girl` don't get loaded, causing the error.

The performance tests don't seem to run in CI anyway, and if they don't we don't seem to track the metrics or raise an alarm if they slow down beyond a certain point.

As of Rails 4, performance testing in this sense isn't part of the main stack and has been extracted into a separate gem. If we don't care about these tests, we should remove them.

### CODE REVIEW

**Comment by heathd** [comment]
good sleuthing. As you say we are not currently tracking/monitoring the performance using this mechanism (whether we should be or not is another conversation).

So :+1: from me for merging this.

**Comment by jamiecobbett** [comment]
:+1:

**Comment by mikejustdoit** [comment]
This is excellent news :+1:

**Comment by tekin** [comment]
Might want to get rid of `environment/benchmark.rb`

**Pull request merged**
