### PR TITLE
Smart quotes ’n’ ellipses…

### PR DESCRIPTION
**Pull request by fofr**
Minor typography improvements to Whitehall.

* Use ellipses (… not ...)
* Use smart quotes http://smartquotesforsmartpeople.com/
* Use en dashes not hyphens

### CODE REVIEW

**Comment by boffbowsh** [comment]
Do these work OK in IE6? I have a vague recollection of having to globally find and replace ’ with `&rsquo;` in a previous lifetime.

**Comment by fofr** [comment]
@boffbowsh Checked in IE6, IE7, IE8 and they work fine.

**Comment by boffbowsh** [comment]
:+1:

**Comment by issyl0** [comment]
:heart_eyes:

**Pull request merged**
