### PR TITLE
Add subtype tracking to design system pages

### PR DESCRIPTION
**Pull request by jyoung-gds**
[Trello ticket link](https://trello.com/c/kaEUP9us/1038-add-custom-dimension-sub-type-tracking-to-pages-events-already-moved-to-design-system)

## What
Add document subtype tracking to pages which have been moved to the design system. Tracking is added to publications, news articles and speeches on the following pages:
- Edit withdrawal message
- Confirm unwithdraw
- Bulk uploads
- Add HTML attachment
- Add file attachment
- Add external attachment
- Confirm unpublish
- Confirm destroy
- Confirm force publish

## Why
This was requested by the performance analysis team to enable a more granular view of data associated with publications, news articles and speeches.

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Comment by jyoung-gds** [comment]
Should this be tested, seeing as there is some logic being added to the views?

**Comment by jyoung-gds** [comment]
Should I separate out some of the code into a partial (e.g. views/admin/tracking/_subtype_tracking.erb.html) to avoid reusing it?

**Comment by dnkrj** [comment]
> Should I separate out some of the code into a partial (e.g. views/admin/tracking/_subtype_tracking.erb.html) to avoid reusing it?

I think that's a good idea! I think that you could just render the same template everywhere without having to remove the speech clause for attachment pages

**Comment by jyoung-gds** [comment]
@dnkrj I've refactored this if you want to take another look

**Review by dnkrj — APPROVED** [review]
Looks good 👍

**Pull request merged**
