### PR TITLE
Touch `StatisticsAnnouncement` on `Publication#save`

### PR DESCRIPTION
**Pull request by gpeng**
When a `Publication` is saved in a state other than draft it should `touch` any associated `StatisticsAnnouncement` to ensure that it is sent to the publishing api.

This wasn't happening causing `StatisticsAnnouncement` objects associated with a published `Publication` not to be redirected.

### CODE REVIEW

**Comment by fofr** [comment]
Do we need a data migration to fix the currently broken ones?

**Comment by gpeng** [comment]
Yes, we do. I was just going to run the code from the previous one we ran back in April but it would be better to add a new one you're right.

**Comment by boffbowsh** [comment]
What @fofr said, but 👍

**Comment by gpeng** [comment]
I've added the data migration if you could cast your eyes over that... @jennyd did some digging and it seems that up to 11/4 they're all good so I've just republished those with a Publication published since April.

**Comment by boffbowsh** [comment]
Bon marche 👍

**Pull request merged**
