### PR TITLE
Reinstate Courts and Tribunals publishing with correct URLs

### PR DESCRIPTION
**Pull request by boffbowsh**
This reinstates Courts and HMCTS Tribunals (aka judicial bodies) into the Publishing and Indexing process with the correct URLs. These were set up in #2114.

### CODE REVIEW

**Comment by tekin** [comment]
Is it possible to get courts working with the publishing and indexing process without overriding `organisation_url` and `organisation_path`? The overridden `organisation_url` method is quite hairy...

**Comment by boffbowsh** [comment]
The overridden helper is used in views too. In theory I could just override `#search_link` with the same logic if this wasn't the case. This seems like a cleanish solution. Having looked back at it now though, I can add more test cases for the helper. I'll do that now.

**Comment by tekin** [comment]
I think it would be safer to push the logic closer to the places where it is needed. The overridden url helper method is highly complex, with multiple nested if/else's and multiple `return` calls, making it hard to reason about and also more likely to introduce bugs. The need for overridden url helpers for documents and editions is an unhappy side-effect of the way documents and editions are modelled with STI. If we can avoid doing the same for other models, that would be great.

How about using the custom `organisation_or_court_path` helper in the views as before, overriding `search_ink` in `Organisation`, and updating `PublishingApiPresenters::Placeholder` to use the `search_link` instead of `Whitehall.url_maker.polymorphic_path(item)` to get the base_path? Would that cover all bases?

**Comment by boffbowsh** [comment]
The `organisation_or_court_path` helper would have to have the same logic, to cover all bases. It didn't before. Putting the logic into `#search_link` would mean either including the `OrganisationsHelper` in the model, or duplicating the code.

I followed the pattern of overriding `_path` and `_url` helpers in `public_document_routes_helper`. The code is now a bit tidier, would you mind having another look please @tekin?

**Comment by boffbowsh** [comment]
This is marked Do Not Merge as we're waiting for owner approval on the courts and tribunals pages. Merging this will make those pages discoverable on the site.

**Comment by evilstreak** [comment]
:+1: A few minor points – this looks good otherwise.

**Comment by boffbowsh** [comment]
Updated.

**Comment by evilstreak** [comment]
:+1: Code looks good

**Pull request merged**
