### PR TITLE
Upgrade mocha to v1.10.0 & fix deprecation warnings

### PR DESCRIPTION
**Pull request by floehopper**
I haven't been able to run *all* the tests locally, but I'm pretty sure I've caught most problems. Hopefully your CI server will be able to confirm.

### CODE REVIEW

**Comment by issyl0** [comment]
Hey @floehopper - thank you for this PR! 💪I've pushed the branch to `origin` so that the tests run.

**Comment by issyl0** [comment]
There are too many to copy/paste here, but on our CI most of the 🥒features are unhappy or skipped because of dependent unhappy ones.

**Comment by floehopper** [comment]
@issyl0 Oh, sorry to hear that. Can you paste details of one of the failures/errors here? Or at least list one of the features which is failing?

**Comment by issyl0** [comment]
@floehopper Here's the [full :cucumber: output in gist form](https://gist.github.com/issyl0/f1a346445534eacfd163f761524e603b).

**Comment by floehopper** [comment]
@issyl0 

> @floehopper Here's the [full 🥒 output in gist form](https://gist.github.com/issyl0/f1a346445534eacfd163f761524e603b).

Oh, thank you. Unfortunately I'm going to need a stack trace to have something to go on. I don't suppose you have an environment where you could run a single failing scenario with a pretty formatter? I'm no Cucumber expert, but something like this...

```
cucumber features/ministers.feature:11 --format pretty
```

**Comment by issyl0** [comment]
I will do that... at some point today... when I get whitehall to work enough to run the tests properly... 😬

**Comment by floehopper** [comment]
@issyl0:

> I will do that... at some point today... when I get whitehall to work enough to run the tests properly... 😬

No worries. I thought that might be the case 😄. Sorry - I didn't mean to cause you extra work! I'll try to get the features running locally when I have time, but it probably won't be until later today.

**Comment by leenagupte** [comment]
> @issyl0
> 
> > @floehopper Here's the [full 🥒 output in gist form](https://gist.github.com/issyl0/f1a346445534eacfd163f761524e603b).
> 
> Oh, thank you. Unfortunately I'm going to need a stack trace to have something to go on. I don't suppose you have an environment where you could run a single failing scenario with a pretty formatter? I'm no Cucumber expert, but something like this...
> 
> ```
> cucumber features/ministers.feature:11 --format pretty
> ```

Stack trace:

```
Feature: Minister pages
As a citizen
I want to be able to view a page gathering information about a minister
So that I can see what government activities they are involved with
As the No 10/Cabinet Office digital team
We want curate the order in which ministers are listed in the Cabinet
section of the ministers page and in the whips section
So that the seniority of members of cabinet and whips are accurately
reflected

  Scenario: The minister belongs to departments                                     # features/ministers.feature:11
  undefined method `stubs' for Services:Module (NoMethodError)
  ./features/support/asset_manager_helper.rb:7:in `Before'
  undefined method `any_instance' for GdsApi::PublishingApiV2:Class (NoMethodError)
  ./features/support/publishing_api.rb:11:in `Before'
    Given "Johnny Macaroon" is the "Minister of Crazy" for the "Department of Woah" # features/step_definitions/minister_steps.rb:13
    When I visit the minister page for "Minister of Crazy"                          # features/step_definitions/minister_steps.rb:27
    Then I should see that the minister is associated with the "Department of Woah" # features/step_definitions/minister_steps.rb:51

Failing Scenarios:
cucumber features/ministers.feature:11 # Scenario: The minister belongs to departments
```

**Comment by issyl0** [comment]
```
Feature: Minister pages
As a citizen
I want to be able to view a page gathering information about a minister
So that I can see what government activities they are involved with
As the No 10/Cabinet Office digital team
We want curate the order in which ministers are listed in the Cabinet
section of the ministers page and in the whips section
So that the seniority of members of cabinet and whips are accurately
reflected
  Scenario: The minister belongs to departments                                     # features/ministers.feature:11
  undefined method `stubs' for Services:Module (NoMethodError)
  ./features/support/asset_manager_helper.rb:7:in `Before'
  undefined method `any_instance' for GdsApi::PublishingApiV2:Class (NoMethodError)
  ./features/support/publishing_api.rb:11:in `Before'
    Given "Johnny Macaroon" is the "Minister of Crazy" for the "Department of Woah" # features/step_definitions/minister_steps.rb:13
    When I visit the minister page for "Minister of Crazy"                          # features/step_definitions/minister_steps.rb:27
    Then I should see that the minister is associated with the "Department of Woah" # features/step_definitions/minister_steps.rb:51
Failing Scenarios:
cucumber features/ministers.feature:11 # Scenario: The minister belongs to departments
```

(Thanks to @leenagupte for offering a working whitehall dev environment!)

**Comment by floehopper** [comment]
@leenagupte @issyl0 Many thanks, both - I'll investigate later today. 😄

**Comment by floehopper** [comment]
I've improved the commit message of the 3rd commit and hopefully fixed the failing features you were seeing in a 4th commit, although I still haven't managed to run *all* the features locally. When you have time it would be great if you can kick off another CI build with these latest changes. Many thanks for your help!

**Comment by issyl0** [comment]
@floehopper I kicked off another CI build. Thank _you_ for saving us a load of work! :star:

**Comment by floehopper** [comment]
@issyl0 Many thanks. It looks like the tests & features have all passed now - is that right?

**Comment by floehopper** [comment]
Yay! 🎉

**Pull request merged**
