### PR TITLE
Move withdraw or unpublish edition page to the GOV.UK Design System

### PR DESCRIPTION
**Pull request by DilwoarH**
## What

Move the unpublishing and withdrawal page to the design system layout

## Why

We are starting to transition the Edition workflow from Bootstrap to the GOV.UK Design System.

https://trello.com/c/0lUcXlG6/617-move-withdraw-or-unpublish-edition-page-to-the-govuk-design-system

## Screenshots

screenshot-whitehall-admin dev gov uk-2022 08 31-12_51_29
screenshot-whitehall-admin dev gov uk-2022 08 31-12_51_53
screenshot-whitehall-admin dev gov uk-2022 08 31-12_52_15
screenshot-whitehall-admin dev gov uk-2022 08 31-12_52_30

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Comment by davidtrussler** [comment]
@DilwoarH This all looks good - only thing is: should there be a way for the user to go back if they don't want to unpublish? That is currently the "cancel" button but I guess is now the "Back" link.

**Comment by nnagewad** [comment]
Beauty!!!

**Review by davidtrussler — APPROVED** [review]
This looks good to me! 👍

**Comment by nnagewad** [comment]
Just checking if the title and caption font-size is set to XL.

**Comment by DilwoarH** [comment]
> Just checking if the title and caption font-size is set to XL.

done in seperate PR #6786

**Pull request merged**
