### PR TITLE
Resetting the font to sans-serif for all things print

### PR DESCRIPTION
**Pull request by russellthorn**
This fixes an odd character bug in some printers unable to print transport font.

### CODE REVIEW

**Comment by edds** [comment]
Is there a way we can do this more generically across all of our applications rather than doing it bespoke per application?

**Comment by russellthorn** [comment]
Well, when we first discussed this you said I'd need to do this across several apps, which I was about to roll out? Ideally doing it once so it can be shared would be far better. Let's discuss that.

**Comment by dsingleton** [comment]
Isn't this done generically across all applications (using the [FET typography mixins](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss#L23-L26))? Whitehall is an exception to that behaviour, as it has it's own [typography mixins](https://github.com/alphagov/whitehall/blob/master/app/assets/stylesheets/frontend/styleguide/_typography.scss), which causes the problem in the first place.

The short term fix would be to replicate if the `is-print` font-stack logic from FET in the Whitehall mixins. Longer term I assume we wouldn't want custom typography for Whitehall, as it just another frontend application, right?

**Comment by dsingleton** [comment]
I think this is superceded by https://github.com/alphagov/whitehall/pull/1960

**Comment by russellthorn** [comment]
:thumbsup:

Will close this.

**Pull request closed without merging**
