### PR TITLE
Fix statistics announcements redirect on unpublish

### PR DESCRIPTION
**Pull request by MatMoore**
When a statistics announcement without an associated publication
is unpublished, it should publish a redirect to the publishing api
so that government frontend can perform the redirect.

A redirect url is already required to unpublish.

### CODE REVIEW

**Comment by MatMoore** [comment]
I think this is not working properly yet because of a conflict with this callback in `PublishesToPublishingApi`:

```
after_commit :publish_to_publishing_api, if: :can_publish_to_publishing_api?
```

```
  def can_publish_to_publishing_api?
    persisted?
  end
```

**Comment by gpeng** [comment]
We used to have a [separate presenter](https://github.com/alphagov/whitehall/pull/2457/files#diff-450e29faa7d56aa1e0f26d8dda2d8824) for this case that looks to have been removed when the `/unpublish` endpoint became a thing, hence the functionality breaking.

To get your callback to run unhindered we could override that method in `StatisticsAnnouncement` to include the logic for unpublished e.g.

```
  def can_publish_to_publishing_api?
    !unpublished? && super
  end
```

or something like that?

**Comment by Rosa-Fox** [comment]
Have been trying to get this to work locally but not going too well!

Two problems are:
- Unpublishing removes the announcement from the db so it won't meet the `persisted?` condition within`super`.
- There is already an [over-riding method](https://github.com/alphagov/whitehall/blob/master/app/models/statistics_announcement.rb#L18) in `StatisticsAnnouncement` that checks that something hasn’t been published. This clashes with what we want to do as something would need to be published to be unpublished.

**Comment by MatMoore** [comment]
@Rosa-Fox It's not actually removed from the DB, it's just hidden by the default scope, so I think it's still counting as persisted, even though it's not normally visible (`StatisticsAnnouncement.unscoped.find` still returns it though).

I just checked this (after finally fixing my dev environment) and saw that the super version of `publication_has_been_published?` is returning true and so is the overridden one. It's also definitely triggering this line: https://github.com/alphagov/whitehall/blob/master/lib/publishes_to_publishing_api.rb#L17

So I think the minimal change is something like @gpeng's idea, just adding `!unpublished? &&` to the overriden method (maybe there's a cleaner way though).

**Comment by MatMoore** [comment]
@Rosa-Fox @gpeng I've pushed a fix for the redirect being overridden and it now works for me locally. Is this ok to merge?

**Pull request merged**
