### PR TITLE
Remove local government email alerts and filtering.

### PR DESCRIPTION
**Pull request by elliotcm**
These are to be handled by e.g. the local government
topic and subtopics: https://www.gov.uk/local-government

https://trello.com/c/GpW8gI5b/199-0-5-remove-local-government-checkbox

### CODE REVIEW

**Comment by tommyp** [comment]
:+1:

**Comment by bradleywright** [comment]
:+1::+1:

**Comment by rboulton** [comment]
Is there a plan to migrate existing subscriptions somehow?

**Comment by elliotcm** [comment]
@rboulton existing subscriptions will continue to operate through whitehall: https://github.com/alphagov/whitehall/pull/2140

**Pull request merged**
