### PR TITLE
Upgrade to rails 4

### PR DESCRIPTION
**Pull request by tekin**
This updates Whitehall to run on Rails 4.0. For the most part the changes deal with various deprecations and breakages due to changes in Rails' behaviour. There are a few key areas where more comprehensive changes were required:

**Localised routing**

The whitehall application patches Rails' routing code to support our particular flavour of localisation URLs, for example:

```
  /government/publications/some-publication
  /government/publications/some-publication.fr
  /government/publications/some-publication.fr.json
```

This patch had to be rewritten as the routing code had changed significantly in the move from Rails 3 to 4 (https://github.com/alphagov/whitehall/commit/73d17ac152cca8c89d48d8f67ff45507119a9f0a).

**Rails routing bug**

There is a bug in the Rails routing code that was causing an issue with some of the localised routing, specifically when generating a localised route with a default format set. A fix has been [submitted to Rails](https://github.com/rails/rails/pull/18627), and a monkey patch added to whitehall to cope with this in the meantime (https://github.com/alphagov/whitehall/commit/6129a6ff38028468726f5c1c5b60f1e6f98234c4).

**friendly_id conflict resolution change**

The Rails 4 compatible version of friendly_id changes behaviour significantly, particularly around slug conflict resolution. Pre-Rails 4, slug conflicts were resolved by appending a sequence number to the end of the slug. friendly_id now resolves conflicts by appending a UUID to the end (simpler solution and also threadsafe). To maintain the previous behaviour in whitehall, the conflict resolution code in friendly_id is being overridden to generate sequential slugs again (https://github.com/alphagov/whitehall/commit/5203d322e66159a3698ad107b1cfd6d116a40509)

**friendly_id magic finders**

Rails 4 compatible friendly_id no longer overrides `ActiveRecord::Base#find` so that it can be passed a slug string as well as an ID number by default. It can be switched back on, but it's not very stable as it requires hooking into ActiveRecord internals (and breaks often with newer versions of ActiveRecord). The preferred method is to use the new `friendly` scope, for example:

```ruby
  Model.friendly.find(slug)
```

To keep the changes in this pull request to a minimum, the magic `find` override has been enabled (https://github.com/alphagov/whitehall/commit/972e039644693354209a8c1a52b76d1b211323ac). Ideally some future work would disable it and move all `find` calls to use the new `friendly` scope.

**Globlize feature/Rails bug workaround**

A change was made to the globalize gem that means a translated model is `touch`ed whenever one of its translations are updated/destroyed (useful if using the `updated_at` timestamp in cache keys). This unfortunately does not interact well with Rails' optimistic locking when attempting to destroy a translated model: the translated model `destroy` triggers the associated translations to be destroyed, which `touch` the translated model, which increments the `lock_version`, which results in the in-memory object becoming stale. This is ultimately a bug in ActiveRecord (it should know not to touch a record that is being destroyed), but fixing that appears to be non-trivial. To get around this, whitehall is now using forked version of globalize that doesn't include the `touch: true` directive on the translations assocation (https://github.com/alphagov/whitehall/commit/95ee80a05018d805e91ca3505596739a481bd040)

**Other Globalize validation issue**

There appears to be a bug in globalize that means presence validations are not being triggered when saving a translation using `update_attributes` (https://github.com/globalize/globalize/issues/401). The workaround for now is to both explicitly set the `locale` attribute and also perform the action in a `I18n.with_locale` block. (https://github.com/alphagov/whitehall/commit/5e6e66581d3dac581e224591cce4069caf6dee9c#diff-095e6f47d7355ba033961aeb9dd441b6R7).

**shared_mustache gem change**

The newest version of sprockets-rails is not correctly choosing the local `templates.js` over the copy in the shared_mustache gem, which was causing the compiled javascript in test mode to not include the compiled mustache templates. This has been resolved by removing the blank `templates.js` from the shared_mustache gem (it's only purpose was so that any app using the shared_mustache gem could include `templates.js` in it's asset manifest without having to actually have a local file present)

**Changes to cookie signing**

Rails 4 introduces a new way to generate and verify signed cookies. It has a mechanism to automatically upgrade old cookies transparently. However, because the new cookies are not backwards compatible, this has intentionally been left off until we are certain that the upgrade has gone smoothly and that we don't need to roll back to the Rails 3 version. Once the dust has settled, steps should be taken to enable the new cookie code and begin the upgrade process. See http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack for more details.

### CODE REVIEW

**Comment by tekin** [comment]
There's a strange thing happening to the `body` text areas on the forms on this branch (currently visible on preview). On this version, the `rows` attribute is not being set, so the text areas are defaulting to two rows. On master, they some how get rendered with `rows` set to 20. Thing is, I can't see anywhere in the app code where they are being set to 20! If anyone has any insight before I dig into this further, let me know /cc @edds

**Comment by jackscotti** [comment]
Tekin, you broke GitHub!

screen shot 2015-01-30 at 09 40 11

**Comment by bradleywright** [comment]
Epic PR of the day :+1:

**Comment by edds** [comment]
@tekin following the apidocs through text areas were initialized using `DEFAULT_TEXT_AREA_OPTIONS` which are defined to have 20 rows if none are specified. http://apidock.com/rails/ActionView/Helpers/InstanceTagMethods

Though looking they have removed that default in rails 4.

**Comment by tekin** [comment]
@edds Uurgh, glad they got rid of that particular piece of magic! I'll get this branch updated to fill in the blanks for text areas without an explicit row count.

**Comment by tekin** [comment]
So looks like my fix for "Other Globalize validation issue" (https://github.com/alphagov/whitehall/commit/5e6e66581d3dac581e224591cce4069caf6dee9c#diff-095e6f47d7355ba033961aeb9dd441b6R7) is causing another issue - although it causes the presence validations to kick-in, setting the `:locale` attribute in `LocalisedModel` will overwrite the `locale` attribute on the `editions` table, i.e. what we use to signify the edition's primary locale. This is causing the primary locale to be changed on an edition when a new translation is added, which makes it appear as a non-english edition.

Looking at this now, I think the presence of an attribute called "locale" on the `editions` table is almost certainly the root cause. I'm going to have to investigate this further.

**Comment by heathd** [comment]
ok I've finished reviewing this. All looks good, nice work! There were quite a few thorny issues to deal with along the way!

My only slight concern is the globalize fork. I'm not clear whether fixes in rails will avoid the lock version issues or not. If we do need to patch globalize, it might be good to also work with them to develop an alternative solution, as it would be good to develop some confidence that we can avoid forking in the medium term.

Obviously there is also the issue with 5e6e665 which you mentioned.

**Comment by tekin** [comment]
This branch now includes a fix for the issue with non-english editions. The fix is to use a column not called "locale" to signify the primary locale of the edition as this conflicts with some of the internal behaviour of globalize: globalize uses a `:locale` key during mass-assignment to signify the locale of the attributes being set. Up to now we got away with it and the locale attribute was being correctly set on the edition table, but this has changed with newer versions of globalize.

**Comment by tekin** [comment]
Nice work on getting a patch for the optimistic locking issue into globalize @heathd! :cake: We'll have to wait until we've got whitehall to Rails 4.2 before we can move back to the main fork though as master breaks compatibility with Rails versions below that. Either that or see if we can get the fix backported to 4-0-stable.

**Comment by tekin** [comment]
Rebased against master

**Comment by heathd** [comment]
Thanks @tekin. Just for the record, here's a link to the PR which has just been merged into globalize https://github.com/globalize/globalize/pull/408

**Comment by heathd** [comment]
Rather than forking globalize, perhaps we could now reference globalize@master

**Comment by tekin** [comment]
Unfortunately not, master only works with Rails 4.2.

**Comment by heathd** [comment]
I've rebased this onto `perforance-improvements-to-document-searches-controller` (which in turn has been rebased on master) in anticipation of that being merged

**Comment by evilstreak** [comment]
:fireworks:

**Comment by fofr** [comment]
:tada: :four: :balloon:

**Comment by tekin** [comment]
🎊💃🎊

**Comment by lazyatom** [comment]
:clap:

**Pull request merged**
