### PR TITLE
Add New and Edit Worldwide Org pages in the GOV.UK Design System

### PR DESCRIPTION
**Pull request by davidgisbey**
## Description

We're moving the Worldwide Org section over to the GOV.UK Design System as part of release 1.12. This moves over the new and edit worldwide org pages.

I've had to extend the single image upload component to handle not rendering anything to do with alt text as worldwide org logos do not require alt text for obvious reasons.

## Screenshots

image

image

image

## Trello card

https://trello.com/c/sabdTg12/324-edit-new-details-page

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

### CODE REVIEW

**Comment by nnagewad** [comment]
Looks good 👍🏽

**Comment by farahTW** [comment]
@davidgisbey  are there any feature tests we should cover?

**Comment by farahTW** [comment]
oks..LGTM

**Review by farahTW — APPROVED** [review]
LGTM

**Pull request merged**
