### PR TITLE
Delete policy and supporting pages code

### PR DESCRIPTION
**Pull request by elliotcm**
Policies are now published through the policy publisher.  Supporting pages are no longer a thing.

Later PRs will be raised to:
- Delete the data & tables
- Rename `Future::Policy` to `Policy`

Sorry for the Very Large Commits, but the nature of the change means doing it en masse was the only way to get it done in a reasonable time.

You *have* to review this commit by commit because Github can't display a diff longer than 300 files.

The true changeset is `356 files changed, 792 insertions(+), 5874 deletions(-)`.

Good luck!

https://trello.com/c/nZiu3ExT/270-remove-policies-and-supporting-pages-from-whitehall

### CODE REVIEW

**Comment by edds** [comment]
Haven't looked at the code but this is awesome. :fireworks:

**Comment by edds** [comment]
You can probably also delete this file now: [_policies.scss](https://github.com/alphagov/whitehall/blob/delete-policy-code/app/assets/stylesheets/frontend/views/_policies.scss)

**Comment by edds** [comment]
I believe you can also delete [_case_studies.html.erb](https://github.com/alphagov/whitehall/blob/delete-policy-code/app/views/case_studies/_case_studies.html.erb) as it was only called from the policies show template.

**Comment by edds** [comment]
I believe you should also be able to delete the translation "document.headings.policies".

**Comment by edds** [comment]
Couple of extra things I think you can now get rid of, but this looks good to me. :+1:

**Comment by elliotcm** [comment]
@edds Done.  Deleted an extra translation while I was at it.

We're now at `358 files changed, 792 insertions(+), 6487 deletions(-)`.

**Comment by edds** [comment]
Tests are failing because the base.scss file is trying to include the file you deleted.

**Comment by elliotcm** [comment]
@edds Updated, and removed some more CSS I noticed while I was at it, please double check the CSS commit.

Now at ` 360 files changed, 792 insertions(+), 6542 deletions(-)`.

**Comment by edds** [comment]
LGTM.

**Pull request merged**
