### PR TITLE
Remove `edition_policy_groups` model.

### PR DESCRIPTION
**Pull request by elliotcm**
This is now handled in the policy publisher.

### CODE REVIEW

**Comment by boffbowsh** [comment]
It scares me that no test changes were needed as part of this PR.

This migration will fail: https://github.com/alphagov/whitehall/blob/master/db/migrate/20150615080039_delete_policies_and_supporting_pages.rb#L19

**Comment by elliotcm** [comment]
@boffbowsh this is a remnant of the giant deletion thingy, literally nothing is calling this at the moment.

That migration has already been run.

**Comment by elliotcm** [comment]
That said, I don't mind removing it from that migration just in case people are a little behind.

**Comment by boffbowsh** [comment]
:+1: then

**Comment by boffbowsh** [comment]
It might be safer, considering it's still *relatively* recent.

**Comment by elliotcm** [comment]
@boffbowsh updated

**Comment by boffbowsh** [comment]
:rocket: :+1:

**Pull request merged**
