### PR TITLE
Bump friendly_id from 5.2.4 to 5.3.0

### PR DESCRIPTION
**Pull request by gclssvglx**
For: https://trello.com/c/rM6VLd6U/1301-audit-dependabot-for-whitehall

Added `extends FriendlyId` to `Attachment` and all classes that inherit from `Attachment` - as recommended [here](https://github.com/norman/friendly_id/blob/9cd4ce2b5d0425aa704872e1334b442cab03c29c/lib/friendly_id/base.rb#L21)...

> A note about single table inheritance (STI): you must extend FriendlyId in all classes that participate in STI, both your parent classes and their children.

Pull `friendly_id :title, use: :scoped, scope: :attachable` from `HtmlAttachment` up into the parent `Attachment` class.

### CODE REVIEW

**Comment by kevindew** [comment]
@gclssvglx Great that you've got this passing. It'd be good if we could document the commit message without the problems we faced, why this code has moved and why we're confident it'll have no impact on the app.

**Comment by gclssvglx** [comment]
Commit message updated.

**Comment by emmabeynon** [comment]
@gclssvglx Thanks for updating the commit message; it's much clearer to me now.  One small point, I don't think we need to include the code before and after in the commit message itself since we can see it in the commit diff.

**Comment by gclssvglx** [comment]
@emmabeynon Thanks for the comments.  Have updated the commit message appropriately.

**Comment by kevindew** [comment]
> @emmabeynon Thanks for the comments. Have updated the commit message appropriately.

You might also want to flag yourself as the commit author as it's moved on a lot since I worked on it. You can do that with `git commit --amend --author='Graham Lewis <graham.lewis@digital.cabinet-office.gov.uk>'`

**Comment by gclssvglx** [comment]
@kevindew Thanks - was going to ask if there was a way to do that!  Commit updated.

**Pull request merged**
