### PR TITLE
Port in accessible autocomplete from content publisher

### PR DESCRIPTION
**Pull request by DilwoarH**
This PR ports in accessible autocomplete from the content publisher

Preview: http://whitehall-admin.dev.gov.uk/component-guide/autocomplete

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### CODE REVIEW

**Comment by DilwoarH** [comment]
> Is it worth considering putting this into the gem instead?

I'd like to do so but not this version, this version isn't well supported. This one: https://github.com/alphagov/accessible-autocomplete - is worth putting into the GEM

**Comment by andysellick** [comment]
In terms of actual components, there's also this one in smart answers, which is a very trimmed down simpler version, again based on the same original code: https://github.com/alphagov/smart-answers/blob/main/app/views/components/_autocomplete.html.erb

**Review by davidgisbey — APPROVED** [review]
awesome we need for the edit page 👍

**Comment by DilwoarH** [comment]
> In terms of actual components, there's also this one in smart answers, which is a very trimmed down simpler version, again based on the same original code: https://github.com/alphagov/smart-answers/blob/main/app/views/components/_autocomplete.html.erb

That's interesting (didn't know this), I'll work on getting these into the components gem

**Pull request merged**
