### PR TITLE
Add the Non-GOV.UK government links tab to the features page

### PR DESCRIPTION
**Pull request by davidgisbey**
## Description

This follows on from #7606 which added the documents tab to the WorldLocationNews#features endpoint.

It adds the non_govuk_government_links tab and the confirm delete offsite link endpoints.

## Screenshot

image

image

## Trello card

https://trello.com/c/YBTlvGI8/54-world-location-features-page-epic-card

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

### CODE REVIEW

**Comment by nnagewad** [comment]
Looks good from the design side.

**Review by CL-GDS — APPROVED** [review]
LGTM, Like the layout of the table on the `_featureable_offsite_links.html.erb` page, very clean and readable, should be the standard on these types. I'll add it to the guide :)

Tests for `confirm_destroy` are needed but I'm sure they'll be covered in other commits as part of the Epic

**Comment by davidgisbey** [comment]
You're def right. Have added one. I'm going to add a bunch of feature specs too. Will open a separate PR for those though 👍

**Comment by nnagewad** [comment]
After a user successfully added a new link:
Topical Events - Features and unfeatures documents

**Pull request merged**
