### PR TITLE
Fix case-[in]sensitivity issue for fractions

### PR DESCRIPTION
**Pull request by boffbowsh**
As most devs <sup>[citation needed]</sup> use Macs with case-insensitive file
systems to work on Whitehall, we should probably not have two versions
of the same file with differently cased names if we can avoid it.

Notably, this breaks the Github for Mac client which is one of the
better and more popular OS X git guis. When you boot the app up it is
confused about seeing `1_X.png` and `1_Y.png`, but only `1_x.png` and
`1_y.png` in the filesystem, so marks the uppercase versions for
deletion.

### CODE REVIEW

**Comment by bradleywright** [comment]
I'm ambivalent about this. "Most devs" should use the officially provided VM to develop, because it avoids issues with incorrect server versions and configuration, most notably MySQL failing to import DB dumps.

**Comment by alext** [comment]
> "Most devs" should use the officially provided VM to develop

It is odd on the dev VM as well, because the dev VM mounts its filesystem from the mac, and therefore only sees one version of these images.

**Comment by boffbowsh** [comment]
We use the VM to develop, but we mount our code directories over NFS from a case-insensitive filesystem and then some use OSX git tools for visual diffing.

**Comment by fofr** [comment]
This looks good to me, and removes something that's been frustrating me for months. :+1:

**Pull request merged**
