### PR TITLE
Remove governance groups

### PR DESCRIPTION
**Pull request by mgrassotti**
Trello: https://trello.com/c/CqAYE3pf/471-delete-format-governance-group-medium#

Create a new data migration to remove governance groups from rummager, so they don’t appear anymore in searches.

### CODE REVIEW

**Comment by boffbowsh** [comment]
👍

**Comment by mgrassotti** [comment]
I added a 404s exception handling.

**Comment by gpeng** [comment]
:+1:

**Comment by mgrassotti** [comment]
I added a data migration to remove Groups data. After that is released, a PR to remove Group model will be also needed.

**Comment by boffbowsh** [comment]
👍

**Pull request merged**
