### PR TITLE
Remove metadata link tracking

### PR DESCRIPTION
**Pull request by fofr**
As part of moving analytics from classic to universal, we’ve audited the custom variables being set and whether they are still being used. Ash identified this variable as being unused and marked it for deletion. It will not be switched over to Universal.

Undoes 7583621517ed47157b3f29c8a42c835443561bb6

## Before merging
* [x] Search and browse confirm this isn't useful

### CODE REVIEW

**Comment by jamiecobbett** [comment]
> Search and browse confirm this isn't useful

Do you mean Finding Things? I don't think Search and Browse exist any longer.

**Comment by rboulton** [comment]
I think you need to talk to @edds who did the work on this.

**Comment by edds** [comment]
I am fine with it. Does the finding things team still want to know which metadata is clicked? It was added to help us think about finding content from whitehall documents.

**Comment by rboulton** [comment]
I think that this might well be of interest.  However, we really need to get this sort of information for much more than just metadata links - clicks on footers, vs related links, etc.

In the current form, this tracking is probably more annoyingly sparse than useful, so I'm all for removing this for now to tidy up the code and free up a custom variable.  We can resurrect this idea for tracking the stuff we actually care about, in future.

**Comment by edds** [comment]
:+1: This looks good to merge to me.

**Pull request merged**
