### PR TITLE
Improve publishing api worker error handling

### PR DESCRIPTION
**Pull request by jamiecobbett**
I was having trouble following the behaviour and intent of the code and understanding these errors when they appeared in Errbit, so I thought I'd tidy it up a bit.

/cc @steventux

### CODE REVIEW

**Comment by boffbowsh** [comment]
This isn't necessarily true. The previous code would allow a retry if the status was a 5XX (by re-raising the error). This new code will swallow all errors even 5XXs and not retry them. I believe the code that shouldn't be retried is a 422, as it's failing validation on the server side.

**Comment by steventux** [comment]
@boffbowsh @jamiecobbett I think this change does what is intended because [only `GdsApi::HTTPClientError`s are rescued now](https://github.com/alphagov/whitehall/commit/f109a7ceaea5e77ce6ae55654b0d4add72345e60#diff-4441da90019510a9f7b8b7f5c500c114R12), and [these are all 4xxs](https://github.com/alphagov/gds-api-adapters/blob/master/lib/gds_api/exceptions.rb#L69).
5xx errors will continue to raise and alert won't they?

**Comment by boffbowsh** [comment]
You're totally right. My bad :) In that case, :+1:

**Comment by jamiecobbett** [comment]
@boffbowsh I've since rebased the changes, but you may have been looking at this branch whilst it had a bad rebase that meant the code was doing what you describe, but thankfully the test was failing correctly.

**Pull request merged**
