### PR TITLE
Autoclose ministerial appointments

### PR DESCRIPTION
**Pull request by elliotcm**
When a government is closed all ministers no longer
hold their roles.  This change saves lots of time
when closing the government and marks the act of
closing a government accordingly dire and protected.

This also prevents the setting of an end date when
creating a new government.

Flow is as follows.

Closed governments remain the same:
screenshot 2015-03-24 15 27 09

Open governments gain a link to "Prepare for closing this government":
screenshot 2015-03-24 15 28 09

This link leads to a page explaining that all ministerial role appointments will be removed, and listing the appointments for review:
screenshot 2015-03-24 15 28 31

[.. cut ..]

screenshot 2015-03-24 15 28 41

Pushing the big red button makes it happen.

https://trello.com/c/xylhahXO/134-when-a-current-government-ends-all-ministerial-appointments-should-do-too

While I was at it I also fixed the return path of the "Cancel" link when editing a government, which is this ticket: https://trello.com/c/wnKFWhip/137-bug-cancel-button-on-create-a-gov-returns-to-wrong-page

### CODE REVIEW

**Comment by elliotcm** [comment]
@tekin updated.

**Comment by elliotcm** [comment]
Product sign-off from @bmwelby on local machine.

**Comment by tekin** [comment]
:+1: I made some additional tweaks to simplify the permissions enforcement. Mainly it was to make the rules on the controller actions whitelist rather than blacklist so it's less likely that destructive actions are left off.

**Comment by elliotcm** [comment]
:+1: to the additions.

**Pull request merged**
