### PR TITLE
Simplify typography scss

### PR DESCRIPTION
**Pull request by dsingleton**
These share a lot of logic/styling with the typography mixins
in the `govuk_frontend_toolkit`, but have slightly 
styling and are missing some behaviours, like switching to
a safer (non-webfont) font for printing.

This brings WH styling slightly more in line with other
frontends, which seems like a good thing.

This does change some styling though, a couple of the
640px breakpoint sizes are different in WH to FET:

- core-48 @ 640: 25px/0.8 => 32px/1
- core-27 @ 640: 19px/1.3 => 20/1.1
- core-24 @ 640: 17px/1.5 => 18px/1.2
- core-19 @ 640: 13px/1.5 => 16px/1.25
- core-16 @ 640: 13px/1.5 => 14px/1.1

After discussion with @edds we think a ship-it and see
approach is probably safe, as this will only affect
some minor cases

### CODE REVIEW

**Comment by edds** [comment]
:+1: This is a great step in the right direction till we have the time to properly remove these `ig-core` variants.

**Comment by dsingleton** [comment]
I'm pretty confident with this. The font size differences are only at `640` breakpoint, and only vary by a pixel or two. 

The biggest variation is in `ig-core-48`, which will shift from 25px to 32px. However, this is only used in 4 places, 3 of which are standard page titles, which will be fine, and once on /how-government-works on minister counts, which set their own font size are breakpoints, including 640.

**Comment by dsingleton** [comment]
I've pushed a few extra commits to this, all cleaning up custom typography mixin usage.

**Comment by edds** [comment]
:+1:

**Pull request merged**
